server:
  port: 8080

homme-service:
  url: ${HOMME_SERVICE_URL:http://localhost:8081}

femme-service:
  url: ${FEMME_SERVICE_URL:http://localhost:8082}

spring:
  application:
    name: index-service
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/index_db
    username: postgres
    password: postgres
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  cloud:
    gateway:
      routes:
        # Routes for Homme Service
        - id: homme-service
          uri: ${homme-service.url}
          predicates:
            - Path=/api/homme/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        
        # Routes for Femme Service
        - id: femme-service
          uri: ${femme-service.url}
          predicates:
            - Path=/api/femme/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        
        # Auth routes (no authentication required)
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation2024ProjetProduitsMicroservices
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
